### ISSUE TITLE
Ability to renew aws credentials without application restart

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba-aws#4]
Not sure about system variables or Java properties, But it seems it could be simply implemented for ```~/.aws/credentials```.

### Environment

- Platform version: 7.2-beta1 

### Description of the bug or enhancement

- Minimal reproducible example
1) Create ```~/.aws/credentials``` file with some incorrect or outdated AIM keys in [default] profile

![image](https://user-images.githubusercontent.com/19840141/73565667-77cfe180-447b-11ea-9315-f334fa14f47e.png)

2) in ``app.properties`` define some existent bucket/region
do not define credentials there! This will activate default credentials provider
```
cuba.amazonS3.region = us-west-1
cuba.amazonS3.bucket = cuba-the-best
```

3) Start the application

4) Open Administration -> External files. And try to upload\download something: ensure it does not work

5) Then correct ```~/.aws/credentials```
![image](https://user-images.githubusercontent.com/19840141/73566095-7521bc00-447c-11ea-8239-ad71a509492a.png)

6) Open Administration -> External files. And try to upload\download something: check if ot starts working

- Expected behavior
The credentials are renewed - read  from ```~/.aws/credentials```. 

- Actual behavior
The credentials are renewed only after the application re-start. 
![image](https://user-images.githubusercontent.com/19840141/73566263-e06b8e00-447c-11ea-9116-2a0c625235ca.png)

**Comment by soraksh** [comment]
Added AmazonS3Manager MBean with `refreshS3Client()` method. It will refresh S3Client with current properties and credentials will be reloaded from file if needed (note that data from system variables or Java properties won't be reloaded).

**Comment by IskandarovRost** [comment]
The Bean method could be scheduled.
